### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by lmaccherone**
executeNext() now correctly indicates that the callback gets responseHeaders as the third parameter

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lmaccherone__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ryancrawcour** [comment]
The JS client SDK is a sub-set of the Node.js so when submitting changes it is best to submit them to the Node.js SDK and let them trickle down to this one. 
Please contribute this change to the Node.js core SDK.

**Comment by lmaccherone** [comment]
That's the second time I have done that. I now took a note as to the
correct one so I don't do it again in the future. I resubmitted on the true
source. This doesn't show up as binary.

**Comment by ryancrawcour** [comment]
Thanks. I've updated the Contribution guidelines for this particular SDK to indicate this.

**Pull request closed without merging**
