### PR TITLE
node support

### PR DESCRIPTION
**Pull request by ashumeow**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ashumeow__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ashumeow** [comment]
Done!

**Comment by ryancrawcour** [comment]
@ashumeow  thanks for the contribution; we're looking at this now but due to the lack of a description from you we are having trouble understanding the purpose of this PR. Could you please explain what you have added. 

It looks like you added support for Travis CI ?

**Comment by azurecla** [comment]
__@ashumeow__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by ashumeow** [comment]
Then, the helloworld.js which i found in readme as sample file.
Example:-
    
    node helloworld.js
And added the build for checking purpose..

**Pull request closed without merging**
