### PR TITLE
JSDoc fix - changed masterkey to masterKey

### PR DESCRIPTION
**Pull request by lmaccherone**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lmaccherone__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by lmaccherone** [comment]
Let me know if this sort of pull request is useful. I'm using the docs now and finding little things.

**Comment by ryancrawcour** [comment]
Yes, definitely useful, thanks! Because the JavaScript client SDK is a sub-set of the Node.js SDK and is in fact generated from this we're thinking about how we accept PRs for this and incorporate it back up the chain. 

But plse, keep sending them while we figure out how to best handle your contributions!

Thanks

**Comment by lmaccherone** [comment]
Can I submit pull requests to the main repo? Is that public?

**Comment by ryancrawcour** [comment]
If by "main repo" you mean the Node.js repo, then yes, it is available - https://github.com/Azure/azure-documentdb-node/tree/master/core_sdk/lib

**Comment by lmaccherone** [comment]
Would it help if I just redid the edits there?

**Comment by lmaccherone** [comment]
OK, I implemented the pull request over in azure-documentdb-node. Hopefully the changes can be merged there.

**Pull request closed without merging**
